Add main header
alan-hadyk/grocify pull request #40
Opened 2023-12-04 17:37 UTC by angulawk

2023-12-06 18:58 UTC, alan-hadyk commented
Problem with a placeholder (on real device):

![Zrzut ekranu 2023-12-6 o 19 58 12](https://github.com/alan-hadyk/grocify/assets/4722055/a39d8a55-cf81-4abc-8a09-d9f393aff201)

2023-12-06 19:02 UTC, alan-hadyk commented
After consideration, I think that "X" should have a width of `20`. Right now, it's too small. Be mindful that height is not the same as width in this icon.

![Zrzut ekranu 2023-12-6 o 19 59 48](https://github.com/alan-hadyk/grocify/assets/4722055/e593ed1a-a08d-44c0-955a-eba5b1ecd9ae)

2023-12-06 20:01 UTC, alan-hadyk commented on client-mobile/src/components/molecules/ExpandableInput/hooks/useExpandableInputState.ts
> +  const ref = useClickOutside<RnView>(() => {
```suggestion
  const animatedViewRef = useClickOutside<RnView>(() => {
```

2023-12-06 20:01 UTC, alan-hadyk commented on client-mobile/src/components/molecules/ExpandableInput/hooks/useExpandableInputState.ts
> +  })
Extract the callback to `closeInput` fn

2023-12-06 20:02 UTC, alan-hadyk commented on client-mobile/src/components/molecules/ExpandableInput/hooks/useExpandableInputState.ts
> +  ref.current?.measure((x, y, width) => {
```suggestion
  ref.current?.measure((_x, _y, width) => {
```

2023-12-06 20:02 UTC, alan-hadyk commented on client-mobile/src/components/molecules/ExpandableInput/hooks/useExpandableInputState.ts
> +  const [containerWidth, setContainerWidth] = useState<number>(0)
```suggestion
  const [animatedContainerWidth, setAnimatedContainerWidth] = useState<number>(0)
```

2023-12-06 20:04 UTC, alan-hadyk commented on client-mobile/src/components/molecules/ExpandableInput/hooks/useExpandableInputState.ts
> +import { TextInput as RnTextInput, View as RnView } from "react-native"
```suggestion
import { TextInput, View } from "react-native"
```

2023-12-06 20:08 UTC, alan-hadyk commented on client-mobile/src/components/molecules/ExpandableInput/hooks/useExpandableInputState.ts
> +
There should be a `useEffect` in this hook that opens and focuses the input whenever the value is not empty.

2023-12-06 20:09 UTC, alan-hadyk commented on client-mobile/src/components/molecules/ExpandableInput/hooks/useExpandableInputState.ts
> +      onChangeText("")
Not sure if `onChangeText("")` is needed here - please verify this.

2023-12-06 20:09 UTC, alan-hadyk commented on client-mobile/src/components/molecules/ExpandableInput/hooks/useExpandableInputStyles.ts
> +  const searchIconStyles = expandableInputDefaultStyles.searchIcon
```suggestion
```

2023-12-06 20:11 UTC, alan-hadyk commented on client-mobile/src/components/molecules/ExpandableInput/hooks/useExpandableInputStyles.ts
> +  const screenWidth = Dimensions.get("window").width
This will be probably needed on a regular basis. Please create a new hook - `client-mobile/src/hooks/useScreenDimensions`, and return `screenWidth` and `screenHeight` from that hook.

2023-12-06 20:12 UTC, alan-hadyk commented on client-mobile/src/components/molecules/ExpandableInput/styles.ts
> +    width: 12,
This icon is not rectangular. Please refer to `TODO` comment in `client-mobile/src/components/atoms/Icon/Icon.tsx`

2023-12-06 20:16 UTC, alan-hadyk commented on client-mobile/src/components/molecules/ExpandableInput/ExpandableInput.tsx
> +import { IconName } from "@client/components/atoms/Icon/@types/Icon"
Please rename this file to `index.tsx`, and do the same for all other components (put `Button` inside `Button` folder). Thanks to this, imports will be better (`@client/components/molecules/ExpandableInput` instead of `@client/components/molecules/ExpandableInput/ExpandableInput`)

2023-12-06 20:19 UTC, alan-hadyk commented on client-mobile/src/components/molecules/Header/Header.tsx
> +  const [value, setSearchPhrase] = useState<string>("")
This state doesn't belong here. Please move it to `HeaderContainer`, and pass via props (`searchInputValue`, `onSearchInputValueChange`)

2023-12-06 20:21 UTC, alan-hadyk commented on client-mobile/src/components/molecules/IconButton/IconButton.tsx
> +  iconName: name,
```suggestion
  iconName,
```

2023-12-06 20:22 UTC, alan-hadyk commented on client-mobile/src/components/molecules/IconButton/IconButton.tsx
> +  */
Please think about this. `IconButton` has more than 1 size, and that will affect the icon size.

2023-12-06 20:22 UTC, alan-hadyk commented on client-mobile/src/components/molecules/IconButton/styles.ts
> +export const iconButtonDefaultStyles: Record<"wrapper", Sx> = {
```suggestion
import { Sx } from "dripsy"

export const iconButtonDefaultStyles: Record<"wrapper", Sx> = {
```

2023-12-06 20:25 UTC, alan-hadyk commented on client-mobile/src/containers/Footer/FooterContainer.tsx
> +// import { Button } from "@client/components/atoms/Button"
Rename to `client-mobile/src/containers/FooterContainer/index.tsx`

2023-12-06 20:26 UTC, alan-hadyk commented on client-mobile/src/containers/Header/HeaderContainer.tsx
> +import { Header } from "@client/components/molecules/Header/Header"
Rename to `client-mobile/src/containers/HeaderContainer/index.tsx`

2023-12-06 20:27 UTC, alan-hadyk commented on client-mobile/src/theme/index.ts
>  }
This declaration could be moved to `client-mobile/src/@types/theme.d.ts`

2023-12-07 20:19 UTC, alan-hadyk commented
Please add https://www.npmjs.com/package/eslint-plugin-react-hooks

2023-12-08 10:51 UTC, alan-hadyk commented
It seems that "X" has disappeared:

![Zrzut ekranu 2023-12-8 o 11 50 51](https://github.com/alan-hadyk/grocify/assets/4722055/8ce1b420-de1a-4a79-82c1-fbc967020e97)

2023-12-08 10:58 UTC, alan-hadyk commented
Placeholder should have a `Gray400` color.

![Zrzut ekranu 2023-12-8 o 11 57 31](https://github.com/alan-hadyk/grocify/assets/4722055/905ee18f-9e35-4373-9610-498eefc949cd)

2023-12-09 13:52 UTC, angulawk commented on client-mobile/src/components/molecules/ExpandableInput/@types/ExpandableInput.ts
> +  onChangeText: (value: string) => void
onChange
Callback that is called when the text input's text changes.

onChangeText
Callback that is called when the text input's text changes. Changed text is passed as a single string argument to the callback handler.

2023-12-10 11:20 UTC, alan-hadyk commented
Don't forget about https://github.com/alan-hadyk/grocify/pull/40#discussion_r1417918539

2023-12-10 12:05 UTC, alan-hadyk requested changes

2023-12-10 12:05 UTC, alan-hadyk commented on client-mobile/src/hooks/useMeasureElement.ts
> +export const useMeasureElement = (elementRef: RefObject<View>) => {
It seems that this hook might be causing unexpected errors:

![Zrzut ekranu 2023-12-10 o 12 56 28](https://github.com/alan-hadyk/grocify/assets/4722055/d4de3eef-a5e6-4354-bbd5-49e145442082)

Please try to use this code (instead of elementRef.current?.measure):
```
const onLayout = useCallback(event => {
    const { x, y, width, height } = event.nativeEvent.layout

    setElementMeasurements({
      height,
      width,
      x,
      y,
    })
  }, []);
```

Return `onLayout` method from this hook, and pass it to `AnimatedView`

2023-12-10 12:05 UTC, alan-hadyk commented on client-mobile/src/components/templates/AppTemplate/index.tsx
> +}
```suggestion
export const AppTemplate: React.FC<IAppTemplateProps> = ({ children }) => <SafeAreaView>{children}</SafeAreaView>
```

2023-12-11 12:26 UTC, alan-hadyk commented on client-mobile/src/hooks/useMeasureElement.ts
> +export const useMeasureElement = (elementRef: RefObject<View>) => {
And rename this hook to `useLayoutMeasurements`

2023-12-11 14:00 UTC, alan-hadyk approved these changes

2023-12-11 14:01 UTC, merged