New shopping list - blank screen
alan-hadyk/grocify pull request #74
Opened 2023-12-22 21:11 UTC by angulawk

2023-12-25 21:49 UTC, alan-hadyk requested changes

2023-12-25 21:49 UTC, alan-hadyk commented on client-mobile/src/components/molecules/ShoppingListButtons/styles.ts
> +    flexBasis: "40",
```suggestion
button: {
    flexBasis: "auto",
    flexGrow: 1,
  },
  recipeButton: {
    flexBasis: "35%",
  },
  wrapper: {
    flexBasis: 40,
    flexDirection: "row",
    gap: "$12",
```

This will ensure that there's always exactly 12 gap between buttons

2023-12-25 21:49 UTC, alan-hadyk commented on client-mobile/src/components/molecules/DateHeader/styles.ts
> +    marginTop: "$12",
As a side note - this should be `$16`, not `$12`

2023-12-25 21:49 UTC, alan-hadyk commented on client-mobile/src/containers/ShoppingListDetailsContainer/index.tsx
> +    </ItemPageTemplate>
This is not "complete" in terms of possible states. We need to account for errors, as well as for loading states. However, this should be done in a separate ticket - https://github.com/alan-hadyk/grocify/issues/83

2023-12-25 21:49 UTC, alan-hadyk commented on client-mobile/src/containers/ShoppingListDetailsContainer/index.tsx
> +export const ShoppingListDetailsContainer: React.FC = () => {
Rename to `ShoppingItemContainer`
```suggestion
export const ShoppingItemContainer: React.FC = () => {
```

2023-12-25 21:49 UTC, alan-hadyk commented on client-mobile/src/components/molecules/ShoppingListButtons/styles.ts
> +export const shoppingListButtonsDefaultStyles: {
```suggestion
export const shoppingListItemButtonsDefaultStyles: {
```

2023-12-25 21:49 UTC, alan-hadyk commented on client-mobile/src/containers/ShoppingListsContainer/index.tsx
> +  const { isLoading, mutateAsync: createShoppingList } = useCreateShoppingList({
We should use `mutate`, not `mutateAsync` here, because `mutateAsync` is a Promise, which might throw unexpected errors.
```suggestion
  const { isLoading, mutate: createShoppingList } = useCreateShoppingList({
```

2023-12-25 21:49 UTC, alan-hadyk commented on client-mobile/src/hoc/withTranslations.tsx
> +    console.log({ locale })
```suggestion
```

2023-12-25 21:49 UTC, alan-hadyk commented on client-mobile/src/hooks/useAsyncEffect.ts
> +}
Extract to `client-mobile/src/hooks/@types/useAsyncEffect` and rename to `IUseAsyncEffect`

2023-12-25 21:49 UTC, alan-hadyk commented on client-mobile/src/lib/internationalization.ts
> +  "en-US": {
```suggestion
  [PreferredLang.En]: {
```

2023-12-25 21:49 UTC, alan-hadyk commented on client-mobile/src/lib/internationalization.ts
> +  pl_PL: {
```suggestion
  [PreferredLang.Pl]: {
```

2023-12-25 21:49 UTC, alan-hadyk commented on client-mobile/src/lib/internationalization.ts
>  const resources = {
```suggestion
import i18n, { ResourceLanguage } from "i18next"
//
const resources: Record<PreferredLang, ResourceLanguage> = {
```

2023-12-25 21:49 UTC, alan-hadyk commented on client-mobile/src/routing/paths.ts
> +  ShoppingList = "/shopping-lists/[id]",
For the sake of clarity
```suggestion
  ShoppingListItem = "/shopping-lists/[id]",
```

2023-12-25 21:49 UTC, alan-hadyk commented on client-mobile/src/translations/@types/index.ts
> +  Delete: string
We'll add this later when it will be actually used.
```suggestion
```

2023-12-25 21:49 UTC, alan-hadyk commented on client-mobile/src/translations/@types/index.ts
> +  Reuse: string
```suggestion
```

2023-12-25 21:49 UTC, alan-hadyk commented on client-mobile/src/translations/PL.ts
> +  "Grocery items will appear here": "Artykuły spoywcze pojawią się tutaj",
```suggestion
  "Grocery items will appear here": "Produkty pojawią się tutaj",
```

2023-12-26 18:16 UTC, angulawk commented on client-mobile/src/app/_layout.tsx
> +    </Stack>
We should consider doing it in a separate task

2023-12-26 19:47 UTC, angulawk commented on client-mobile/src/components/molecules/IconButton/styles.ts
> +            color: "$gray400",
I think it is not needed

2023-12-27 10:54 UTC, alan-hadyk commented
Color of the text when Button is loading is wrong. This also applies to disabled button.

UI:

![Zrzut ekranu 2023-12-27 o 11 53 56](https://github.com/alan-hadyk/grocify/assets/4722055/30098b62-f08f-4b81-a69e-3217a2aa57a4)

Designs:

![Zrzut ekranu 2023-12-27 o 11 53 39](https://github.com/alan-hadyk/grocify/assets/4722055/5eca97ce-2afb-461e-afd0-c312e56d09e8)

2023-12-27 11:29 UTC, alan-hadyk requested changes

2023-12-27 11:29 UTC, alan-hadyk commented on client-mobile/src/components/molecules/ItemWrapper/styles.ts
> +export const ItemWrapperDefaultStyles: {
```suggestion
export const itemWrapperDefaultStyles: {
```

2023-12-27 11:29 UTC, alan-hadyk commented on client-mobile/src/components/molecules/ItemWrapper/@types/index.ts
> +export interface IItemWrapper {
```suggestion
export interface IItemWrapperProps {
```

2023-12-27 11:29 UTC, alan-hadyk commented on client-mobile/src/app/shopping-lists/[id].tsx
> +const ShoppingListPage: React.FC = () => (
```suggestion
const ShoppingListItemPage: React.FC = () => (
```

2023-12-27 11:29 UTC, alan-hadyk commented on client-mobile/src/containers/ShoppingItemContainer/index.tsx
> +export const ShoppingItemContainer: React.FC = () => {
```suggestion
export const ShoppingListItemContainer: React.FC = () => {
```

2023-12-27 11:29 UTC, alan-hadyk commented on client-mobile/src/components/molecules/ShoppingListItemHeader/@types/index.ts
> +export interface IShoppingListItemHeader {
```suggestion
export interface IShoppingListItemHeaderProps {
```

2023-12-27 11:29 UTC, alan-hadyk commented on client-mobile/src/containers/ShoppingItemContainer/index.tsx
> +              }}
Maybe you could remove this `sx` and instead add `marginBottom: "$16"` to `ShoppingListItemHeader`?

2023-12-27 11:31 UTC, alan-hadyk commented on client-mobile/src/app/_layout.tsx
> +    </Stack>
https://github.com/alan-hadyk/grocify/issues/89

2023-12-27 11:32 UTC, alan-hadyk commented on client-mobile/src/containers/FooterContainer/index.tsx
> +  // TODO: Animate footer appearing and disappearing somehow
https://github.com/alan-hadyk/grocify/issues/89

2023-12-27 11:32 UTC, alan-hadyk commented on client-mobile/src/containers/HeaderContainer/index.tsx
> +  // TODO: Animate header appearing and disappearing somehow
https://github.com/alan-hadyk/grocify/issues/89

2023-12-27 12:03 UTC, alan-hadyk approved these changes

2023-12-27 12:03 UTC, merged