Add grocery items - basic functionality
alan-hadyk/grocify pull request #95
Opened 2023-12-28 21:21 UTC by angulawk

2024-01-07 14:57 UTC, alan-hadyk commented
Text inside `Banner` has a line height of `20`:

![Zrzut ekranu 2024-01-7 o 15 56 54](https://github.com/alan-hadyk/grocify/assets/4722055/e94c2ecf-ca55-4b98-ae9e-d6473544e8b8)

It should have `18` (130%):

![Zrzut ekranu 2024-01-7 o 15 56 44](https://github.com/alan-hadyk/grocify/assets/4722055/b0eb6efa-bb73-4eaa-9747-ee7af0518879)

2024-01-07 15:08 UTC, alan-hadyk commented
When input is focused, it should have a black border.

![Zrzut ekranu 2024-01-7 o 16 05 53](https://github.com/alan-hadyk/grocify/assets/4722055/86bad6c4-dc1c-49b7-bccb-79e9d89874b9)

Did you implement designs for input? - [https://www.figma.com/file/X7eTkEpLdUMMXXOpdz2Mp4/Corporate-Identity-%2B-UI?type=design&node-id=511-1615&mode=design&t=iyJC4OUI0olv6naa-4](https://www.figma.com/file/X7eTkEpLdUMMXXOpdz2Mp4/Corporate-Identity-%2B-UI?type=design&node-id=511-1615&mode=design&t=iyJC4OUI0olv6naa-4)

Same applies to disabled input:

![Zrzut ekranu 2024-01-7 o 16 08 40](https://github.com/alan-hadyk/grocify/assets/4722055/9504edbe-6867-445a-a718-fec4cfba7ca6)

2024-01-07 15:11 UTC, alan-hadyk commented
There's something wrong with the vertical alignment of ingredient name:

![Zrzut ekranu 2024-01-7 o 16 10 21](https://github.com/alan-hadyk/grocify/assets/4722055/d1e7f5b9-4996-4576-b554-56c6d94b58f3)
![Zrzut ekranu 2024-01-7 o 16 10 26](https://github.com/alan-hadyk/grocify/assets/4722055/3d7c69ba-79cf-4fa7-82c2-e0ae2922886a)

2024-01-07 15:12 UTC, alan-hadyk commented
When the amount in counter input is large enough, input width should increase to show the full value:

![Zrzut ekranu 2024-01-7 o 16 11 30](https://github.com/alan-hadyk/grocify/assets/4722055/f92eadf8-4651-40bc-b975-a1b23015a9e3)

2024-01-07 15:15 UTC, alan-hadyk commented
`paddingVertical` of Multiselect item should be `10`, not `12`:

![Zrzut ekranu 2024-01-7 o 16 14 40](https://github.com/alan-hadyk/grocify/assets/4722055/c1df6130-de84-40cb-adbe-bb60d8a4f708)

2024-01-07 15:18 UTC, alan-hadyk commented
Somehow, the width of the checkmark is `15`:

![Zrzut ekranu 2024-01-7 o 16 16 12](https://github.com/alan-hadyk/grocify/assets/4722055/48bc85cf-01be-40ef-8857-d20e2a6deac1)

It should be `14`:

![Zrzut ekranu 2024-01-7 o 16 16 43](https://github.com/alan-hadyk/grocify/assets/4722055/acd6fad9-75e9-4b79-abbb-841e24c8db66)

2024-01-07 15:21 UTC, alan-hadyk commented
When increase (or decrease) icon button is active, it has a gray border:

![Zrzut ekranu 2024-01-7 o 16 18 37](https://github.com/alan-hadyk/grocify/assets/4722055/b3f6c302-30dd-4e50-a130-d4177ce662d6)

It should have a green border (Green500):

![Zrzut ekranu 2024-01-7 o 16 18 10](https://github.com/alan-hadyk/grocify/assets/4722055/52780e71-cd99-437e-95ae-bbfba04675d8)

2024-01-07 15:23 UTC, alan-hadyk commented
Selected Multi select item has a `#14E195` (Green400) border:

![Zrzut ekranu 2024-01-7 o 16 20 53](https://github.com/alan-hadyk/grocify/assets/4722055/f4099fc1-417d-41d5-8d1a-0c463519ea25)

It should have a Green500:

![Zrzut ekranu 2024-01-7 o 16 22 41](https://github.com/alan-hadyk/grocify/assets/4722055/ebfc88aa-f5bb-4496-a706-e26b694a07e8)

2024-01-07 15:29 UTC, alan-hadyk commented
Please limit the width of ingredient name, because long names might break the UI:

![Zrzut ekranu 2024-01-7 o 16 29 49](https://github.com/alan-hadyk/grocify/assets/4722055/f425c7bf-072c-41e1-be6b-2f30d8fce8b0)

2024-01-07 15:35 UTC, alan-hadyk commented
Right after adding new ingredient, when quantity is not changed, user is not able to select or deselect any ingredient.

2024-01-07 15:37 UTC, alan-hadyk commented
There's something slightly wrong with a counter appearing and disappearing (during selecting) when the item position doesn't change (notice border bottom):

![appear-disappear](https://github.com/alan-hadyk/grocify/assets/4722055/ef8f3f20-de26-4e92-8aeb-9eedda1b343c)

2024-01-07 15:39 UTC, alan-hadyk commented
There should be a fading white gradient above the button:

![Zrzut ekranu 2024-01-7 o 16 38 31](https://github.com/alan-hadyk/grocify/assets/4722055/a00af5d7-715a-4115-8ad1-cffcf5b3aa8c)

Design:

![Zrzut ekranu 2024-01-7 o 16 38 25](https://github.com/alan-hadyk/grocify/assets/4722055/33cd2b81-3e6f-4647-9874-bc192b360d60)

2024-01-07 16:09 UTC, alan-hadyk commented
If I try to input `1.5` inside Counter input, it becomes `NaN`:

![Zrzut ekranu 2024-01-7 o 17 08 50](https://github.com/alan-hadyk/grocify/assets/4722055/6c813e51-12c2-410f-a1a1-425a6b6e2452)

Trying to input `1,5` is not possible.

2024-01-07 16:54 UTC, alan-hadyk commented
Using the counter input on the real device causes the multi-select item to be reordered:


https://github.com/alan-hadyk/grocify/assets/4722055/0e0c9075-16ab-48ac-8bdd-ed369de02208


Also, this causes a warning:

![image](https://github.com/alan-hadyk/grocify/assets/4722055/8bee1d81-5f6d-4e94-80ad-51de50e1b8f0)

2024-01-07 19:49 UTC, alan-hadyk requested changes
This is review part 1. I'll try to review the rest tomorrow.

2024-01-07 19:49 UTC, alan-hadyk commented on client-mobile/src/components/molecules/MultiSelect/helpers/calculateUpdatedItems.ts
> +}
Slightly refactored version

```suggestion
export const calculateUpdatedItems = (
  items: TMultiSelectFieldItemType[],
  updatedItem: Pick<IMultiSelectItemProps, "id" | "isSelected" | "quantity">,
) => {
  let itemIndex: number | undefined
  let previousQuantity: number | undefined
  let numberOfSelectedItems = 0

  const updatedItems = items.map((item, index) => {
    if (item.id === updatedItem.id) {
      itemIndex = index
      previousQuantity = item.quantity
      return { ...item, ...updatedItem }
    }

    if (item.isSelected) {
      numberOfSelectedItems++
    }

    return item
  })

  if (itemIndex !== undefined && previousQuantity === updatedItem.quantity) {
    const item = updatedItems[itemIndex]

    updatedItems.splice(itemIndex, 1)

    const newPosition = item.isSelected ? 0 : numberOfSelectedItems
    item.quantity = item.isSelected ? 1 : 0

    updatedItems.splice(newPosition, 0, item)
  }

  return updatedItems
}
```

2024-01-07 19:49 UTC, alan-hadyk commented on client-mobile/src/components/molecules/MultiSelect/index.tsx
> +            disabled={disabled}
`disabled={true}` doesn't change anything in the styles of MultiSelect.

Updated designs - https://www.figma.com/file/X7eTkEpLdUMMXXOpdz2Mp4/Corporate-Identity-%2B-UI?type=design&node-id=475-1997&mode=design&t=iyJC4OUI0olv6naa-4

2024-01-07 19:49 UTC, alan-hadyk commented on client-mobile/src/components/molecules/MultiSelect/index.tsx
> +          />
This could be simplified:

```suggestion
<MultiSelectItem
            {...item}
            isFirst={index === 0}
            onSelectItem={handleSelectItem}
            disabled={disabled}
          />
```

`handleSelectItem` can be extracted into `useMutliSelectState` hook

2024-01-07 19:49 UTC, alan-hadyk commented on client-mobile/src/components/molecules/MultiSelect/styles.ts
> +}
```suggestion
export const multiSelectDefaultStyles: Sx = {
    flexDirection: "column",
    flexGrow: 1,
    height: "100%",
  }
```

2024-01-07 19:49 UTC, alan-hadyk commented on client-mobile/src/components/molecules/MultiSelectField/index.tsx
> +      <MultiSelect disabled={disabled} onChange={onChange} estimatedItemSize={44} items={items} />
I forgot about this, but `estimatedItemSize` should be a required prop passed to `MultiSelectField` component

2024-01-07 19:49 UTC, alan-hadyk commented on client-mobile/src/components/molecules/MultiSelectItem/index.tsx
> +        </View>
Please extract this into `atoms/Checkbox`

2024-01-07 19:49 UTC, alan-hadyk commented on client-mobile/src/components/molecules/MultiSelectItem/index.tsx
> +        </View>
Also, size is `14`, not `15`

2024-01-07 19:49 UTC, alan-hadyk commented on client-mobile/src/components/molecules/MultiSelectItem/styles.ts
> +    paddingY: isSelected ? "$10" : "$12",
```suggestion
    paddingY: "$10",
```

2024-01-07 19:49 UTC, alan-hadyk commented on client-mobile/src/components/organisms/UpdateGroceryItemsForm/hooks/useUpdateGroceryItemsFormState.ts
> +  }
fields, setValue, watch don't have to be returned from this hook - they're not used.

2024-01-07 19:49 UTC, alan-hadyk commented on client-mobile/src/components/organisms/UpdateGroceryItemsForm/index.tsx
> +  const getButtonText = () => {
```suggestion
  const getButtonText = (): keyof ITranslation => {
```

Also, please move this function to `useUpdateGroceryItemsFormState`.

2024-01-07 19:49 UTC, alan-hadyk commented on client-mobile/src/components/organisms/UpdateGroceryItemsForm/index.tsx
> +        />
Missing prop:
```suggestion
        <AddIngredientForm
          isAddingIngredient={isAddingIngredient}
          disabled={isUpdatingGroceryItems}
          onAddIngredient={(data) => onAddIngredient(data, unshiftIngredientInFormIngredients)}
        />
```

2024-01-07 19:49 UTC, alan-hadyk commented on client-mobile/src/components/organisms/UpdateGroceryItemsForm/index.tsx
> +      />
```suggestion
      <Button
        disabled={isAddingIngredient}
        iconName={IconName.Plus}
        text={getButtonText()}
        size={ButtonSize.LargeFixed}
        onPress={handleSubmit(handleUpdateGroceryItems)}
        sx={button}
        isLoading={isUpdatingGroceryItems}
      />
```

2024-01-08 13:53 UTC, alan-hadyk requested changes

2024-01-08 13:53 UTC, alan-hadyk commented on client-mobile/src/containers/ShoppingListItemContainer/provider/index.tsx
> +export const AddGroceryItemModalProvider = ({ children }: any) => {
```suggestion
export const ShoppingListItemProvider: React.FC<IShoppingListItemProviderProps> = ({ children }) => {
```

2024-01-08 13:53 UTC, alan-hadyk commented on client-mobile/src/containers/ShoppingListItemContainer/provider/index.tsx
> +export const useModalContext = () => useContext(ModalContext)
```suggestion
export const useShoppingListItemContext = () => useContext(ShoppingListItemContext)
```

2024-01-08 13:53 UTC, alan-hadyk commented on client-mobile/src/containers/ShoppingListItemContainer/sections/ShoppingListItemFooter/index.tsx
> +    Array.isArray(shoppingList?.ingredients) && shoppingList.ingredients.length > 0
Please extract to `useShoppingListItemFooterState`

2024-01-08 13:53 UTC, alan-hadyk commented on client-mobile/src/containers/ShoppingListItemContainer/sections/ShoppingListItemFooter/index.tsx
> +    />
Those buttons should be disabled when the shopping list is loading.

2024-01-08 13:53 UTC, alan-hadyk commented on client-mobile/src/models/ingredientModel.ts
> +        );
We need to make sure that there are foreign keys:

```suggestion
      CREATE TABLE IF NOT EXISTS ingredients (
          id TEXT PRIMARY KEY,
          name TEXT NOT NULL CHECK(length(name) <= 100),
          unit TEXT,
          last_category_id TEXT,
          created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (unit) REFERENCES units(id)
        );
```

2024-01-08 13:53 UTC, alan-hadyk commented on client-mobile/src/models/ingredientModel.ts
> +        );
Additionally, please modify `useAsyncEffect` hook in `client-mobile/src/hooks/useLocalDbInit.ts`:

```
useAsyncEffect(
    async () => {
      try {
        await databaseClient.transactionAsync(async (tx) => {
          await tx.executeSqlAsync(`
            PRAGMA foreign_keys = ON;
          `)
        })

        await UnitModel.initSchema()
        await IngredientModel.initSchema()
        await ShoppingListModel.initSchema()
        
        setIsDbInitialized(true)
      } catch (error) {
        setDbInitError(error as Error)
      }
    },
    async () => {},
    [],
  )
```

2024-01-08 13:53 UTC, alan-hadyk commented on client-mobile/src/models/shoppingListIngredientsModel.ts
> +import { CreateIngredientInput, Ingredient } from "@client/api/schema"
Please delete this file.

2024-01-08 13:53 UTC, alan-hadyk commented on client-mobile/src/models/shoppingListModel.ts
> +          quantity REAL NOT NULL
Foreign keys:

```suggestion
          id TEXT PRIMARY KEY,
          shopping_list_id TEXT NOT NULL,
          ingredient_id TEXT NOT NULL,
          category_id TEXT,
          quantity REAL NOT NULL,
          FOREIGN KEY (shopping_list_id) REFERENCES shopping_lists(id),
          FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
```

2024-01-08 13:53 UTC, alan-hadyk commented on client-mobile/src/models/unitModel.ts
> +          name TEXT NOT NULL,
```suggestion
          name TEXT NOT NULL CHECK(length(name) <= 100),
```

2024-01-08 13:53 UTC, alan-hadyk commented on client-mobile/src/theme/index.ts
> +  $18: 18,
This isn't going to be used, so you can delete it.
```suggestion
```

2024-01-08 13:53 UTC, alan-hadyk commented on client-mobile/src/translations/@types/index.ts
> +  }
```suggestion
  errorProblemWithAddingNewIngredient: string
```

2024-01-08 13:53 UTC, alan-hadyk commented on client-mobile/src/translations/EN.ts
> +  },
```suggestion
  errorProblemWithAddingNewIngredient: "There was a problem with adding a new ingredient",
```

2024-01-08 13:53 UTC, alan-hadyk commented on client-mobile/src/translations/PL.ts
> +  },
```suggestion
  errorProblemWithAddingNewIngredient:
      "Podczas dodawania nowego składnika wystąpił błąd",
```

2024-01-08 13:53 UTC, alan-hadyk commented on client-mobile/src/translations/PL.ts
> +    "Wpisz nazwę i jednostkę aby dodać pierwszy produkt.",
```suggestion
    "Wpisz nazwę i jednostkę, żeby dodać pierwszy produkt.",
```

2024-01-09 16:14 UTC, angulawk commented on client-mobile/src/components/molecules/AddIngredientForm/styles.ts
> +    flexBasis: 40,
yes, it's needed to keep correct width of Unit and Name fields in AddGroceryItems modal

2024-01-09 16:53 UTC, angulawk commented on client-mobile/src/components/molecules/InputField/@types/index.ts
> +  onInputFieldBlur?: () => void
no, it is not needed

2024-01-10 14:27 UTC, angulawk commented on client-mobile/src/translations/PL.ts
> +    "Wpisz nazwę i jednostkę aby dodać pierwszy produkt.",
I prefer "aby" :D

2024-01-12 17:19 UTC, alan-hadyk commented
Banner text is too small - it has `fontSize: 14`, it should have `20`

![Zrzut ekranu 2024-01-12 o 18 18 47](https://github.com/alan-hadyk/grocify/assets/4722055/12d527f6-776b-4486-ad82-9b8073f1d99a)

2024-01-12 17:51 UTC, alan-hadyk commented
After a few clicks, disabled input gains a black border:

![Zrzut ekranu 2024-01-12 o 18 27 51](https://github.com/alan-hadyk/grocify/assets/4722055/8b6bf06f-b348-4df8-8eec-f450f5da03fb)

2024-01-12 18:09 UTC, alan-hadyk commented
Elements in add ingredient form overflow desired width:

![Zrzut ekranu 2024-01-12 o 19 08 48](https://github.com/alan-hadyk/grocify/assets/4722055/18015e2e-5c8d-48ec-98c9-c15c1d03926b)

2024-01-13 12:28 UTC, alan-hadyk commented
Shadow above footer menu disappeared.

![Zrzut ekranu 2024-01-13 o 13 27 43](https://github.com/alan-hadyk/grocify/assets/4722055/fbac818c-1a1f-4504-b4bf-b40b4ac767cf)

2024-01-13 13:37 UTC, alan-hadyk requested changes

2024-01-13 13:37 UTC, alan-hadyk commented on client-mobile/src/components/organisms/UpdateGroceryItemsForm/styles.ts
> +  childrenWrapper: {
Those aren't really `children`, so maybe `fieldsWrapper` instead?
```suggestion
  fieldsWrapper: {
```

2024-01-13 13:37 UTC, alan-hadyk commented on client-mobile/src/theme/@types/index.ts
> +  SuperFast = 50,
Is `SuperFast` used anywhere?

2024-01-13 13:37 UTC, alan-hadyk commented on client-mobile/src/theme/index.ts
> +        height: 100,
`height: 100` ? Is that a correct value?

2024-01-13 13:37 UTC, alan-hadyk commented on client-mobile/src/translations/EN.ts
> +  errorMaxLength: "Maximum {{length}} signs",
Let's be more precise.
```suggestion
  errorMaxLength: "{{actualLength}}/{{length}} characters",
```

2024-01-13 13:37 UTC, alan-hadyk commented on client-mobile/src/translations/PL.ts
> +  errorMaxLength: "Maksymalnie {{length}} znaków",
```suggestion
errorMaxLength: "{{actualLength}}/{{length}} znaków",
```

2024-01-13 13:37 UTC, alan-hadyk commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Please delete this file

2024-01-13 21:11 UTC, angulawk commented on client-mobile/src/components/molecules/Input/hooks/useInputState.ts
> +      onChangeText?.(isNotNumericValue ? ("" as never) : (value as never))
we do not, in fact all we need is to pass value to onChangeText

2024-01-14 20:51 UTC, alan-hadyk commented
`client-mobile/src/components/molecules/Counter/index.tsx`:
![Zrzut ekranu 2024-01-14 o 21 50 50](https://github.com/alan-hadyk/grocify/assets/4722055/6922f959-ac83-4a9d-a6d2-d16ab1515709)

`client-mobile/src/components/molecules/SubtitleWithIcon/index.tsx`:
![Zrzut ekranu 2024-01-14 o 21 51 20](https://github.com/alan-hadyk/grocify/assets/4722055/798db75e-6f03-4f81-9e86-e50f76159b45)

2024-01-14 21:04 UTC, alan-hadyk requested changes

2024-01-14 21:04 UTC, alan-hadyk commented on client-mobile/src/components/molecules/AddIngredientForm/hooks/useErrorTypeState.ts
> +        values: { length: "100" },
This is going to need a second variable - `actualLength`. You'll have to pass it to this hook.

2024-01-15 13:43 UTC, angulawk commented on client-mobile/src/components/molecules/Counter/@types/index.ts
> +  inputOuterWrapperSx?: Sx
Why it is not resolved? I fixed it

2024-01-15 13:45 UTC, angulawk commented on client-mobile/src/containers/ShoppingListItemContainer/index.tsx
> +          <ShoppingListItemFooter disabled={isShoppingListLoading} />
Why this is not resolved?I solved it

2024-01-15 13:46 UTC, angulawk commented on client-mobile/src/components/molecules/AddIngredientForm/hooks/useErrorTypeState.ts
> +        values: { length: "100" },
why?

2024-01-15 15:20 UTC, alan-hadyk commented on client-mobile/src/containers/ShoppingListItemContainer/index.tsx
> +          <ShoppingListItemFooter disabled={isShoppingListLoading} />
Yes, but there's still `client-mobile/src/containers/ShoppingListItemContainer/sections/ShoppingListItemFooter/@types/index.ts` file (unused), and there's `disabled` prop in `client-mobile/src/containers/ShoppingListItemContainer/sections/ShoppingListItemFooter/index.tsx`

2024-01-15 15:20 UTC, alan-hadyk commented on client-mobile/src/components/molecules/AddIngredientForm/hooks/useErrorTypeState.ts
> +        values: { length: "100" },
Look at the translation: `errorMaxLength: "{{actualLength}}/{{length}} characters",`

2024-01-16 19:01 UTC, alan-hadyk approved these changes

2024-01-16 19:01 UTC, merged